[wokwi]
version = 1
firmware = '.pio\build\esp32-s3-devkitm-1\firmware.bin'
elf = '.pio\build\esp32-s3-devkitm-1\firmware.elf'

[mqtt]
broker = "test.mosquitto.org"
topics = ["deposito/humedad", "deposito/temperatura", "deposito/luz", "deposito/presionAtmosferica"]